config {
  type: "view",
  schema: "thelook_ecommerce_dataform_gold",
  description: "Monthly sales",
  tags: ["gold_layer"]
}

SELECT
  FORMAT_DATE("%Y-%m",created_at) as month,
  ROUND(SUM(sale_price * num_of_item), 2) AS revenue,
  COUNT(DISTINCT order_id) AS order_count,
  COUNT(DISTINCT user_id) AS number_of_customers
FROM
    ${ref("non_cancelled_or_returned_order_items")}
GROUP BY month
ORDER BY revenue DESC