config {
  type: "view",
  schema: "thelook_ecommerce_dataform_gold",
  description: "Revenue By Age Groups",
  tags: ["gold_layer"]
}

SELECT
  ${common.ageBucket("u.age")} AS age_group,
  COUNT(DISTINCT nc_oi.user_id) AS num_customers,
  SUM(num_of_item) AS quantity_purchased,
  ROUND(SUM(sale_price * num_of_item), 2) AS revenue
FROM ${ref("non_cancelled_or_returned_order_items")} AS nc_oi
INNER JOIN ${ref("users")} AS u
ON nc_oi.user_id = u.id
GROUP BY age_group
ORDER BY num_customers DESC